##############################################################################
# GitHub Actions Workflow for volesti to build tests with GCC
#
# Copyright (c) 2020-2021 Vissarion Fisikopoulos
#
# Licensed under GNU LGPL.3, see LICENCE file
##############################################################################
name: cmake-gcc

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.compilers }}
    strategy:
          fail-fast: false
          matrix:
            compilers: [g++-9]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - run: sudo apt-get update || true;
             sudo apt-get install ${{ matrix.compilers }} lp-solve;
             sudo apt-get install cmake libblkid-dev e2fslibs-dev libboost-all-dev libaudit-dev;
             sudo apt-get install python3;
             sudo apt-get install python-numpy;
             for dir in $(ls examples); do
                   cd ${GITHUB_WORKSPACE}/examples/"$dir";
                   #  cmake . -DLP_SOLVE=/usr/lib/lpsolve/liblpsolve55.so;
                   cd ../..;
             done;
             rm -rf build;
             mkdir build;
             cd build;
             cmake -D CMAKE_CXX_COMPILER=${{ matrix.compilers }} -D DISABLE_NLP_ORACLES=ON -D USE_MKL=OFF ../test;
             make;
             ctest --verbose;      